# Produccion - H2 persistent database
spring.datasource.url=jdbc:h2:file:./data/insumos;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD:sa}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.h2.console.enabled=false

# Server config
server.port=${PORT:8080}
